# This is a basic workflow to help you get started with Actions

name: EMU_test_MacOS12

on:
  workflow_dispatch:

jobs:
  run-emulator:
    runs-on: macos-12

    steps:
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Create Android emulator
        run: |
          # install the hardware acceleration
          echo " Installing Hardware Acceleration Manager..."
          sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "extras;intel;Hardware_Accelerated_Execution_Manager"
          # brew install intel-haxm
          sysctl kern.hv_support
          sdkmanager --install "system-images;android-27;google_apis;x86_64"
          echo "no" | avdmanager --verbose create avd --force --name TestAvd123 --abi google_apis/x86_64 --package 'system-images;android-27;google_apis;x86_64'
          echo "AVD created:"
          "$ANDROID_HOME/emulator/emulator" -list-avds
            
          echo "Starting the Android emulator..."
          export ANDROID_EMULATOR_DEBUG=1
          nohup "$ANDROID_HOME/emulator/emulator" -avd TestAvd123 -accel on -gpu swiftshader_indirect -no-snapshot-load 2>&1 &
          $ANDROID_HOME/platform-tools/adb wait-for-device
          echo "Emulator has finished booting"
          $ANDROID_HOME/platform-tools/adb devices
          sleep 45
          screencapture screenshot.jpg
          $ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png

