# This is a basic workflow to help you get started with Actions

name: EMU_test_MacOS12

on:
  workflow_dispatch:
jobs:
  test:
    env:
      APK_DIRECTORY: 'android/app/build/outputs/apk'
      RELEASE_APK_DIRECTORY: 'android/app/build/outputs/apk/releaseE2E'
      APK_PATH: 'android/app/build/outputs/apk/releaseE2E/app-releaseE2E.apk'
      DECOMPILED_BUILD_DIRECTORY: 'android/app/build/outputs/apk/releaseE2E/decompiled-apk'

    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: install apktools
        run: brew install apktool

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: js-dep-${{ hashFiles('package-lock.json') }}

      - name: install
        run: npm install

      - name: Cache Native Build
        id: cached-native-build
        uses: actions/cache@v3
        with:
          path: android/app/build/outputs/apk
          key: android-bundle-${{hashFiles('android/build.gradle')}}-${{hashFiles('android/app/build.gradle')}}

      - name: Generate android Simulator build
        if: steps.cached-native-build.outputs.cache-hit != 'true'
        run: npx detox build --configuration android.emu.release

      - name: Swap JS Bundle and assets
        if: steps.cached-native-build.outputs.cache-hit == 'true'
        run: |
          mkdir dist
          npx react-native bundle --platform android --dev false --entry-file index.js --reset-cache --minify false --bundle-output dist/index.android.bundle --assets-dest dist/assets
          node_modules/react-native/sdks/hermesc/osx-bin/hermesc -O -emit-binary -output-source-map -out=dist/index.android.bundle.hbc dist/index.android.bundle

          mv dist/index.android.bundle.hbc ${{env.DECOMPILED_BUILD_DIRECTORY}}/assets/index.android.bundle
          rsync -a dist/assets/ ${{env.DECOMPILED_BUILD_DIRECTORY}}/res
          apktool b --output ${{env.APK_PATH}} -f -d ${{env.DECOMPILED_BUILD_DIRECTORY}}
          echo android | $ANDROID_HOME/build-tools/33.0.2/apksigner sign --ks android/app/debug.keystore ${{env.APK_PATH}}

      - name: prep detox
        run: npx detox rebuild-framework-cache

      - name: start adb
        run: |
          $ANDROID_HOME/platform-tools/adb start-server

      - name: start logger
        run: adb logcat | grep ReactNativeJS > logcat.txt

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: npx detox test --configuration android.emu.release
          avd-name: testAVD
          profile: pixel_6_pro

      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logcat.txt

      - name: cache prep
        if: steps.cached-native-build.outputs.cache-hit != 'true'
        run: apktool d --output ${{env.DECOMPILED_BUILD_DIRECTORY}} ${{env.APK_PATH}}
