# This is a basic workflow to help you get started with Actions

name: EMU_test_MacOS12

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: install apktool
        run: |
          brew install apktool
          brew install --cask android-sdk

      - name: try apksigner
        run: apksigner

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: js-dep-${{ hashFiles('package-lock.json') }}

      - name: install
        run: npm install

      - name: Setup ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - name: Cache Native Build
        id: cached-native-build
        uses: actions/cache@v3
        with:
          path: decompiled-apk
          key: android-bundle-${{hashFiles('android/build.gradle')}}-${{hashFiles('android/app/build.gradle')}}

      - name: Generate android Simulator build
        if: steps.cached-native-build.outputs.cache-hit != 'true'
        run: npx detox build --configuration android.emu.release

      - name: Swap JS Bundle and assets
        if: steps.cached-native-build.outputs.cache-hit == 'true'
        run: |
          APK_NAME=app-releaseE2E.apk
          ORIGINAL_APK_DIRECTORY=android/app/build/outputs/apk/releaseE2E
          DECOMPILED_BUILD_DIRECTORY=decompiled-apk

          mkdir dist
          mkdir -p $ORIGINAL_APK_DIRECTORY
          npx react-native bundle --platform android --dev false --entry-file index.js --reset-cache --minify false --bundle-output dist/index.android.bundle --assets-dest dist/assets
          node_modules/react-native/sdks/hermesc/osx-bin/hermesc -O -emit-binary -output-source-map -out=dist/index.android.bundle.hbc dist/index.android.bundle

          mv dist/index.android.bundle.hbc $DECOMPILED_BUILD_DIRECTORY/assets/index.android.bundle
          rsync -a dist/assets/ $DECOMPILED_BUILD_DIRECTORY/res
          apktool b --output $ORIGINAL_APK_DIRECTORY/$APK_NAME -f -d $DECOMPILED_BUILD_DIRECTORY
          apksigner sign --ks android/app/debug.keystore -storepass android -keypass android $ORIGINAL_APK_DIRECTORY/$APK_NAME

      - name: prep detox
        run: npx detox rebuild-framework-cache

      - name: start adb
        run: |
          $ANDROID_HOME/platform-tools/adb start-server
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: npx detox test --configuration android.emu.release
          avd-name: testAVD
          profile: Nexus 6

      - name: cache prep
        if: steps.cached-native-build.outputs.cache-hit != 'true'
        run: |
          APK_NAME=app-releaseE2E.apk
          ORIGINAL_APK_DIRECTORY=android/app/build/outputs/apk/releaseE2E

          apktool d --output decompiled-apk $ORIGINAL_APK_DIRECTORY/$APK_NAME
