# This is a basic workflow to help you get started with Actions

name: EMU_test_MacOS12

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: js-dep-${{ hashFiles('package-lock.json') }}

      - name: install
        run: npm install

      - name: Setup ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - name: Generate android Simulator build
        run: npx detox build --configuration android.emu.release

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: npx detox test --configuration android.emu.release
