name: Build Android App

on:
  workflow_dispatch:

jobs:
  build-android-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: android-js-dep-${{ hashFiles('package-lock.json') }}

      - name: install
        run: npm install

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: print
        run: java -version

      - name: Setup Android SDK
        run: sudo apt update && sudo apt install android-sdk

      - name: ls
        run: |
          export ANDROID_SDK=$ANDROID_HOME/cmdline-tools/latest/bin
          export PATH=$ANDROID_SDK/emulator:$ANDROID_SDK/tools:${ANDROID_SDK}/tools/bin:${ANDROID_SDK}/platform-tools:$PATH
          sdkmanager --list | grep system-images

      - name: d
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n TestAVD -k "system-images;android-30;google_apis;x86" --device "Pixel_4"
          $ANDROID_HOME/cmdline-tools/latest/bin/emulator -list-avds
          $ANDROID_HOME/cmdline-tools/latest/bin/emulator @TestAVD
          ls

      - name: d
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n TestAVD -d pixel --package "system-images;android-32;google_apis;x86_64"

      - name: Create bundle
        run: |
          $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "system-images;android-31;google_apis_playstore;x86_64"
          echo "no" | $ANDROID_SDK_ROOT/tools/bin/avdmanager --verbose create avd --force --name "my_android_31" --package "system-images;android-31;google_apis_playstore;x86_64" --tag "google_apis_playstore" --abi "x86_64"
