name: Build and test iOS App

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-ios-app:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # - uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Install JS dependencies
        env:
          JOBS: 'MAX'
        run: yarn install --immutable

      - name: Install apple simulator
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Setup ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - name: Setup Cocoapods
        run: npm run setup

      - name: Get bundle version
        id: version
        run: echo "IOS_VERSION=$(/usr/libexec/PlistBuddy -c "print :CFBundleVersion" ./ios/YourAwesomeProject/Info.plist)" >> $GITHUB_OUTPUT

      - name: Cache Native Build
        id: cached-native-build
        uses: actions/cache@v3
        with:
          path: ios/build/Build/Products/Release-iphonesimulator/gather.app
          key: ios-bundle-V${{ steps.version.outputs.IOS_VERSION }}

      - name: Generate iOS Simulator build
        if: steps.cached-native-build.outputs.cache-hit != 'true'
        run: detox build --configuration ios.sim.release

      - name: Swap JS Bundle and assets
        run: |
          if [[ -f ios/build/Build/Products/Release-iphonesimulator/gather.app/main.jsbundle ]]; then
            echo "$FILE exists!"
          else
            npm run build:compile
            cp /tmp/output.bundle ios/build/Build/Products/Release-iphonesimulator/gather.app/main.jsbundle
            cp /tmp/output.assets/assets ios/build/Build/Products/Release-iphonesimulator/gather.app/assets
          fi

      - name: Cleanup JS Bundle
        working-directory: ios/build/Build/Products/Release-iphonesimulator/gather.app
        if: steps.cached-native-build.outputs.cache-hit != 'true'
        run: rm -rf main.jsbundle assets
